# Site settings

url: "http://briguy52.github.io"
title: "Brian Lin"
description: "The personal website of Brian M. Lin"
keywords: "brian, lin, duke, university, robotics, club, engineer, hardware, 3d printing"
favicon: "/img/favicon.ico"
black-favicon: "/img/donutCatSmall.jpg"
#google-tracking-id: "UA-66934256-1" 
#disqus-shortname: "aronbordin"

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  About: 'about'
  Blog: 'blog'
  Career: 'career'
  #Awards: 'awards'
  Contact: 'contact'

# About variables
background-img: "../img/aerobat.jpg"
me-img: "/img/pilotMountain.jpg"

# Blog variables
paginate: 15

paginate_path: "blog/page:num"

post-preview-words: 200

fb-share: True
twitter-share: True
reddit-share: True

# Career variables

events:
  - image: "/img/career/robotics.png"
    date: "August 2015 - Present"
    description: "Joined the Duke Robotics Clubs' Electronics team!"
  - image: "/img/career/rasPi.ico"
    date: "August 2015 - Present"
    description: "Building a wearable Raspberry Pi text recognizer with the Duke CS Department"
  - image: "/img/career/clairVista.jpeg"
    date: "2015 Summer"
    description: "A summer of web development working with WebRTC, Polymer 1.0, and an AWS LAMP stack"
  - image: "/img/career/duke.png"
    date: "Fall 2014 - Present"
    description: "Started college!"

#awards:
# - title: "OBFEP - Brazilian Physics Olympiad - Bronze Medal"
#    date: "2014"


# First image of the Career timeline
career-img: "/img/career/computer.png"

# Social networks variables (many more available: facebook, flickr, dribbble, pinterest, instagram, tumblr etc.)
social:
  - title: "facebook"
    url: "https://www.facebook.com/brian.lin.5059"
  - title: "github"
    url: "https://github.com/briguy52"
  - title: "linkedin"
    url: "www.linkedin.com/in/brianmlin"

404-img: "/img/eww.gif"

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "info.mk", "vendor"]
