# Site settings
title: Brian Michael Lin
email: bri@nmlin.org
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Bad Painter
github_username:  briguy52
# Build settings
markdown: kramdown

# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

auto: true # automatically update your jekyll
server: true # runs a local server
paginate: 10 # pagination basted on number of posts
exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh', 'style.scss'] # files to exclude
